############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "News"
url = "/news"
weight = 2

[[main]]
name = "Research"
url = "/research"
weight = 3

[[main]]
name = "People"
url = "/people"
weight = 4


[[main]]
parent = "People"
name = "Tom Shi"
url = "/tom-shi"

[[main]]
name = "Publication"
url = "/publication"
weight = 5


[[main]]
parent = "People"
name = "Team Member"
url = "/team-member"

[[main]]
name = "Join Our Team"
url = "/join our team"
weight = 6

[[main]]
parent = "Join Our Team"
name = “join our team”
url = "/join our team"
weight = 61

[[main]]
parent = "Join Our Team"
name = “Contact”
url = "/contact"
weight = 62

# footer menu

[[footer]]
name = "News"
url = "/news"
weight = 1

[[footer]]
name = "Research"
url = "/research"
weight = 2

[[footer]]
name = "People"
url = "/team member"
weight = 3

[[footer]]
name = "People"
url = "/tom shi"
weight = 3

[[footer]]
name = "Publication"
url = "/publication"
weight = 4

[[footer]]
name = "Join Our Team"
url = "/join our team"
weight = 5













