############# English navigation ##############

# Top nav

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "News"
url = "/news/"
weight = 2

[[main]]
name = "Research"
url = "/research/"
weight = 3

[[main]]
name = "People"
identifier = "people"
url = "/people/"
weight = 4

[[main]]
parent = "people"
name = "Tom Shi"
url = "/tom-shi/"
weight = 41

[[main]]
parent = "people"
name = "Team Members"
url = "/authors/"
weight = 42

[[main]]
name = "Publication"
url = "/publication/"
weight = 5

# Parent: Join Our Team
[[main]]
name = "Join Our Team"
identifier = "join"
url = "/join-our-team/"
weight = 6

# Child: Opportunities
[[main]]
parent = "join"
name = "Opportunities"
url = "/join-our-team/"
weight = 61

# Child: Contact
[[main]]
parent = "join"
name = "Contact"
url = "/join-our-team/contact/"
weight = 62

# footer menu

[[footer]]
name = "News"
url = "/news"
weight = 1

[[footer]]
name = "Research"
url = "/research"
weight = 2

[[footer]]
name = "People"
url = "/team member"
weight = 3

[[footer]]
name = "People"
url = "/tom shi"
weight = 3

[[footer]]
name = "Publication"
url = "/publication"
weight = 4

[[footer]]
name = "Join Our Team"
url = "/join our team"
weight = 5
















