############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Research"
url = "/research"
weight = 2

[[main]]
name = "People"
url = "/people"
weight = 3

[[main]]
parent = "People"
name = "Team member"
url = "/team member"

[[main]]
parent = "People"
name = "Tom Shi"
url = "/tom shi"

[[main]]
name = "Publication"
url = "/publication"
weight = 4

[[main]]
name = "News"
url = "/news"
weight = 5


[[main]]
parent = "News"
name = "Contact"
url = "/contact"

[[main]]
parent = "News"
name = "Authors"
url = "/authors"



# footer menu
[[footer]]
name = "Research"
url = "/research"
weight = 1

[[footer]]
name = "People"
url = "/people"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
